### PR TITLE
Respect the target architecture

### PR DESCRIPTION
**Pull request by guenhter**
Allow the installation of the cli also on aarch64 by respecting the target architecture.

### CODE REVIEW

**Comment by guenhter** [comment]
Thx for the fast merge. When can I expect a new release in the Galaxy repo?

**Comment by guenhter** [comment]
@deekayen When do you think a new release will be available in the Galaxy repo?

**Comment by deekayen** [comment]
@guenhter 1.1.0 is available now.

**Comment by guenhter** [comment]
Wow, this was quick. Thanks a lot!

**Pull request merged**
